# Generated by Django 2.1.7 on 2019-03-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20190319_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catstatus',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
