version : '3'

services:
    db:
        image: postgres
        volumes:
            - postgres_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=cat_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    
    django:
        build: .
        command: python manage.py migrate
        command:
            - bash
            - -c
            - python manage.py runserver 0.0.0.0:8000
        environment:
            - DJANGO_DEBUG=True
            - DB_HOST=db
            - DB_NAME=cat_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_PORT=5432
        volumes:
            - .:/code
        ports:
            - "3000:8000"
        depends_on:
            - db

volumes:
    postgres_db:
