version : '3'

services:
    nginx:
      image: nginx:latest
      ports :
        - "80:80"
      volumes:
        - .:/code
        - .:/etc/nginx/conf.d
      depends_on:
        - django
    db:
        image: postgres
        volumes:
            - postgres_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=cat_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    
    django:
        build: .
        command:
            - bash
            - -c
            - gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
        environment:
            - DJANGO_DEBUG=False
            - DB_HOST=db
            - DB_NAME=cat_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_PORT=5432
        volumes:
            - .:/code
        expose:
          - "8000"
        depends_on:
            - db

volumes:
    postgres_db:
