# Generated by Django 2.1.7 on 2019-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20190319_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
